XR_SOURCE_FILES += \
                   drivers/src/driver/chip/flashchip/flash_chip.c     \
                   drivers/src/driver/chip/flashchip/flash_chip_cfg.c  \
		   drivers/src/driver/chip/flashchip/flash_P25QXXH.c  \
                   drivers/src/driver/chip/hal_icache.c \
                   drivers/src/driver/chip/hal_dcache.c  \
                   drivers/src/driver/chip/hal_adc.c                  \
                   drivers/src/driver/chip/hal_board.c                \
                   drivers/src/driver/chip/hal_ccm.c                  \
                   drivers/src/driver/chip/hal_crypto.c               \
                   drivers/src/driver/chip/hal_dma.c                  \
                   drivers/src/driver/chip/hal_dmic.c                 \
                   drivers/src/driver/chip/hal_efuse.c                \
                   drivers/src/driver/chip/hal_flash.c                \
                   drivers/src/driver/chip/hal_flashctrl.c            \
                   drivers/src/driver/chip/hal_global.c               \
                   drivers/src/driver/chip/hal_gpio.c                 \
                   drivers/src/driver/chip/hal_i2c.c                  \
                   drivers/src/driver/chip/hal_i2s.c                  \
                   drivers/src/driver/chip/hal_irrx.c                 \
                   drivers/src/driver/chip/hal_irtx.c                 \
                   drivers/src/driver/chip/hal_nvic.c                 \
                   drivers/src/driver/chip/hal_prcm.c                 \
                   drivers/src/driver/chip/hal_pwm.c                  \
                   drivers/src/driver/chip/hal_rtc.c                  \
                   drivers/src/driver/chip/hal_spi.c                  \
                   drivers/src/driver/chip/hal_spinlock.c             \
                   drivers/src/driver/chip/hal_timer.c                \
                   drivers/src/driver/chip/hal_uart.c                 \
                   drivers/src/driver/chip/hal_util.c                 \
                   drivers/src/driver/chip/hal_wakeup.c               \
                   drivers/src/driver/chip/hal_wdg.c                  \
                   drivers/src/driver/chip/hal_xip.c                  \
                   drivers/src/driver/chip/hal_swd.c                  \
                   drivers/src/driver/chip/sdmmc/core.c               \
                   drivers/src/driver/chip/sdmmc/hal_sdhost.c         \
                   drivers/src/driver/chip/sdmmc/sd.c                 \
                   drivers/src/driver/chip/sdmmc/mmc.c               \
                   drivers/src/driver/chip/sdmmc/quirks.c         \
                   drivers/src/driver/chip/sdmmc/sdio.c         \
                   drivers/src/driver/chip/system_chip.c

